server:
    port: 8080
    display-name: spring-boot

spring:
    datasource:
        name: dataSource
        url: jdbc:mysql://127.0.0.1:3306/rxb_test
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    aop:
      auto: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.test.model

  # Log 配置 级别大写 TRACE|DEBUG|INFO|WARN|ERROR
  logging:
    level:
      #root: INFO
      com.test: DEBUG
      com.ibatis: DEBUG
      java.sql: DEBUG
